### PR TITLE
SLE-782: Fragments for Sloop

### PR DESCRIPTION
**Pull request by thahnen**
We are creating Sloop artifacts based on the JRE for macOS (x64/aarch64), Linux (x64/aarch64) and Windows (x64). For everything else we have a fallback bundle to provide their own JRE.

### CODE REVIEW

**Review by henryju — CHANGES_REQUESTED** [review]
The noarch fragment seems to be installed in all cases, so it means we have twice the size of sloop downloaded for most cases (the noarch and the platform-specific). Ideally we should have the noarch only installed when no other fragment is suitable.

**Comment by henryju** [comment]
image

**Comment by thahnen** [comment]
@henryju the issue was fixed with the `Eclipse-PlatformFilter` now set as well in the MANIFEST.MF of the no-arch fragment

**Comment by thahnen** [comment]
This PR is fucked up by rebasing -.-

**Pull request closed without merging**
