### PR TITLE
BUILD-3457 fix dogfooding

### PR DESCRIPTION
**Pull request by julien-carsique-sonarsource**
Use the builder container
Install AWS CLI, gettext-base (envsubst)
Fix Cirrus artifact download URL

### CODE REVIEW

**Comment by julien-carsique-sonarsource** [comment]
e114121 test commit to remove before merge

**Review by thahnen — APPROVED** [review]
LGTM! Now it works like a charm, tested the update site with a local Eclipse installation.

Please remove the test commit and then you can merge!

**Comment by julien-carsique-sonarsource** [comment]
Tested with https://cirrus-ci.com/task/6012465524244480

**Comment by thahnen** [comment]
Hi @julien-carsique-sonarsource, I think you have to re-schedule a build. Somehow the latest one did not start.

**Pull request merged**
