### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by algonell**
Fix typos in documentation, comments, etc.

### CODE REVIEW

**Comment by thahnen** [comment]
Please remove this automated service from our repository.

**Comment by algonell** [comment]
@thahnen What do you mean?

**Comment by thahnen** [comment]
@algonell this looks like you used some form of service that finds typos in our repo and that just searches + replaces.

I'm very happy to have the typos fixed on user-facing things like log messages or texts displayed in the UI (or even the README.md if it has a benefit), but I would be happier to have this done actually by hand and by case (e.g. [HERE](https://github.com/SonarSource/sonarlint-eclipse/pull/748/files#diff-5d6cf92db3da136c91fade3e970d824901a41ff02907bce5e8a2dc2c30c52354) is a change on variable name in a test project, touching this does not serve a purpose but rather pollutes the Git history.) But as a whole, this looks like automation ran over the project without the personal assessment if this makes sense or not - a typo in a comment is a typo, but changing this is not necessary when you know what I mean.

If I'm mistaken by guessing this was done via a service (your GitHub profile history indicated it too), then I'd like to apologize. If you want to provide the typos on user-facing things, as mentioned above, please re-open this PR and aggregate the changes into one commit.
After that, we will proceed with validation and cherry-picking it with your contributor information, as external PRs cannot run the CI.

**Comment by algonell** [comment]
@thahnen You are right, I am using [codespell](https://github.com/codespell-project/codespell/) to detect misspellings.

Recently I've been trying to improve/help every open source project I love and SonarLint's Eclipse plugin is one of them!

I've tried to keep the changes as tiny (and conceptually intact) as possible.

Let me review everything again and squash them to a single commit.

**Comment by thahnen** [comment]
@algonell, thanks for the clarification!
Thanks for providing the *WHY* on these changes, this is much appreciated as well as you enjoying this plug-in :bowing_man:

On my side I owe you an apology then for my initial, a bit harsh response. Looking forward to your updated PR!

**Comment by algonell** [comment]
@thahnen Thank you!

**Pull request closed without merging**
